[package]
name = "validator_derive_tests"
version = "0.1.1"
authors = ["Vincent Prouillet <hello@vincentprouillet.com>"]
edition = "2018"

[dev-dependencies]
validator = { version = "0.13", path = "../validator", features = ["phone", "card", "unic", "derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
trybuild = "1.0"
regex = "1"
lazy_static = "1"
