[package]
name = "validator"
version = "0.11.0"
authors = ["Vincent Prouillet <hello@vincentprouillet.com"]
license = "MIT"
description = "Common validation functions (email, url, length, ...) and trait - to be used with `validator_derive`"
homepage = "https://github.com/Keats/validator"
repository = "https://github.com/Keats/validator"
keywords = ["validation", "api", "validator"]
edition = "2018"

[dependencies]
url = "2"
regex = "1"
lazy_static = "1"
idna = "0.2"
serde = "1"
serde_derive = "1"
serde_json = "1"
validator_types = { version = "0.11", path = "../validator_types" }
validator_derive = { version = "0.11", path = "../validator_derive", optional = true }
card-validate = { version = "2.2", optional = true }
phonenumber = { version = "0.2", optional = true }
unic-ucd-common = { version = "0.9", optional = true }

[features]
phone = ["phonenumber"]
card = ["card-validate"]
unic = ["unic-ucd-common"]
derive = ["validator_derive"]