[package]
name = "validator_derive"
version = "0.3.0"
authors = ["Vincent Prouillet <vincent@wearewizards.io>"]
license = "MIT"
description = "Macros 1.1 implementation of #[derive(Validate)]"
homepage = "https://github.com/Keats/validator"
repository = "https://github.com/Keats/validator"
keywords = ["validation", "api", "validator"]

[lib]
proc-macro = true

[dependencies]
syn = "0.10"
quote = "0.3"

[dev-dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
compiletest_rs = "0.2"
regex = "0.2"
lazy_static = "0.2"

[dependencies.validator]
# path = "../validator"
version = "0.3.0"
