[package]
name = "validator_derive"
version = "0.15.0"
authors = ["Vincent Prouillet <hello@vincentprouillet.com"]
license = "MIT"
description = "Macros 1.1 implementation of #[derive(Validate)]"
homepage = "https://github.com/Keats/validator"
repository = "https://github.com/Keats/validator"
keywords = ["validation", "api", "validator"]
edition = "2018"

[lib]
proc-macro = true

[features]
phone = ["validator_types/phone"]
card = ["validator_types/card"]
unic = ["validator_types/unic"]

[dependencies]
syn = { version = "1", features = ["extra-traits"] }
quote = "1"
proc-macro2 = "1"
proc-macro-error = "1"
if_chain = "1"
validator_types = { version = "0.15", path = "../validator_types" }
regex = "1.5.5"
lazy_static = "1"


