name: ci
on: [push, pull_request]

jobs:
  test_validator:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: 1.81.0 # MSRV, sometimes it changes because of compiler test issues
          - rust: stable
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build System Info
        run: rustc --version
      - name: Tests
        run: |
          cargo build --no-default-features
          cargo test --no-default-features
          cargo build --features unic --features derive --features card
          cargo test  --features unic --features derive --features card
  test_validator-nightly:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: nightly
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: ${{ matrix.rust }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build System Info
        run: rustc --version
      - name: Tests
        run:
          cargo build --no-default-features
          cargo test --no-default-features
          cargo build --features all
          cargo test  --features all