name: ci
on: [push, pull_request]

jobs:
  test_validator:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Extract Rust version from Cargo.toml
        run: |
          MSRV=$(sed -n 's/^rust-version = "\([^"]*\)"/\1/p' Cargo.toml)
          echo "rust-version: $MSRV"
          echo "MSRV=$MSRV" >> $GITHUB_ENV
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable # actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.MSRV }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build System Info
        run: rustc --version
      - name: Tests
        run: |
          cargo build --no-default-features
          cargo test --no-default-features
          cargo build --features derive --features card
          cargo test --features derive --features card
  test_validator-nightly:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: nightly
    steps:
      - uses: actions/checkout@v5
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build System Info
        run: rustc --version
      - name: Tests
        run: |
          cargo build --no-default-features
          cargo test --no-default-features
          cargo build --all-features
          cargo test --all-features