name: ci
on: [push, pull_request]

jobs:
  test_validator:
    name: Continuous integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - rust: 1.70.0 # MSRV
          - rust: stable
          - rust: nightly
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
      - name: Build System Info
        run: rustc --version
      - name: Tests
        run: |
          cargo build --all-features
          cargo test --all-features
          cargo build --no-default-features
          cargo test --no-default-features